[package]
name = "rust_os"
version = "0.1.0"
authors = ["Ramon van Sprundel <ramonvansprundel@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6" #future versions no longer work
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
